Sprint1
oier-elorrieta/E3_T5_PROG_GI pull request #1
Opened 2024-02-08 09:22 UTC by ibai-elorrieta

2024-02-08 11:10 UTC, oier-elorrieta requested changes
Kontzeptu arazo batzuk ikusten ditut. Zeozer azaltzea nahi baduzue edo ez bada ulertzen 12.30 tan bilera bat egin ahal dut zuekin.

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/JUnit/AretoTest.java
> +//            JDatePicker jDatePicker = new JDatePicker(); // Aquí creamos una instancia de JDatePicker
Masterrera ez dugu sartuko komentatutako koderik.
Kodea euskaraz egongo da.

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/Modelo/Areto.java
> +	Saioa[] SaioaList = new Saioa[5];
Zertarako gordeko ditugu saioak aretoan?

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/Modelo/Erosketak.java
> +	Sarrera[] SarreraList = new Sarrera[5];
Bakarrik 5 sarrera erosi ahal izango dira gehienez erosketa bakoitzean?

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/Modelo/Saioa.java
> +import org.jdatepicker.JDatePicker;
JDatePicker POJO batean? Zertarako behar dugu klase sinple batean interfaze grafikoko elementu bat?

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/Modelo/Saioa.java
> +    Karteldegia[] karteldegiaList = new Karteldegia[5];
50 pelikula badaude, saio bat sortzen den bakoitzean, guztiak kargatuko dituzue?

2024-02-08 11:10 UTC, oier-elorrieta commented on Erronka3/src/Modelo/Zinema.java
> +	Saioa[] SaioalistArray = new Saioa[5];
5 saio eta 5 areto gehienez?

2024-02-08 11:23 UTC, OierZub requested changes

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Karteldegia.java
> +	Pelikula[] pelikulaList = new Pelikula[5];
5 Pelikula? zergaitik 5?

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Areto.java
> +	Saioa[] SaioaList = new Saioa[5];
Zergaitik 5 saio? Zertarako saioak areto barruan?

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Zinema.java
> +	Saioa[] SaioalistArray = new Saioa[5];
Zergaitik ematen diozue tamaina?

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Saioa.java
> +    Karteldegia[] karteldegiaList = new Karteldegia[5];
Saioak Karteldegi list bat izango du????

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Saioa.java
> +    private JDatePicker jDatePicker;
Hau ez dakit zer egiten duen hemen.

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Zinema.java
> +	Areto[] Aretolistarray = new Areto[5];
idem

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Sarrera.java
> +	Saioa[] SaioalistArray = new Saioa[5];
idem

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Erosketak.java
> +	Sarrera[] SarreraList = new Sarrera[5];
Beti da 5?

2024-02-08 11:23 UTC, OierZub commented on Erronka3/src/Modelo/Erosketak.java
> +	private int id_erosketak;
Hau ez luke lehenengo aributua izan behar?

2024-02-09 10:34 UTC, OierZub approved these changes
Animo 2. sprintarekin

2024-02-09 10:42 UTC, oier-elorrieta approved these changes

2024-02-09 10:43 UTC, merged